# SwiftLint Configuration File

disabled_rules:
  # ERRORS IN PROJECT CURRENTLY
  - cyclomatic_complexity
  - identifier_name
  - function_body_length
  - force_cast
  - force_try
  - line_length
  - file_length
  - type_body_length
  # WARNINGS IN PROJECT CURRENTLY
  - todo
  - orphaned_doc_comment
  - opening_brace
  - blanket_disable_command
  - for_where
  - trailing_whitespace
  - vertical_whitespace
  - void_function_in_ternary
  - empty_enum_arguments
  - closure_parameter_position

identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 41
