// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

/// Manages loading and parsing of declension contracts
class DeclensionManager {
  static let shared = DeclensionManager()

  private init() {}

  /// Loads declension cases for a language
  func loadDeclensions(language: String) -> [NavigationLevel]? {
    let languageCode = language.lowercased()

    // Load contract JSON file (e.g., "de.json")
    guard let jsonResourcePath = Bundle.main.path(
      forResource: "\(languageCode)",
      ofType: "json"
    ) else {
      NSLog("Declensions not found: \(languageCode).json")
      return nil
    }

    do {
      let data = try Data(contentsOf: URL(fileURLWithPath: jsonResourcePath))
      guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
            let declensionsDict = json["declensions"] as? [String: [String: Any]] else {
        return nil
      }

      // Sort by numeric keys
      let sortedKeys = declensionsDict.keys.sorted { Int($0) ?? 0 < Int($1) ?? 0 }

      var cases: [NavigationLevel] = []

      for key in sortedKeys {
        guard let declension = declensionsDict[key],
              let title = declension["title"] as? String,
              let forms = declension["forms"] as? [String: Any] else {
          continue
        }

        let options = parseForms(forms, parentTitle: title)
        cases.append(NavigationLevel(title: title, options: options))
      }

      return cases
    } catch {
      NSLog("Error loading declensions \(languageCode)/declensions.json: \(error)")
      return nil
    }
  }

  /// Recursively parses forms with optional displayValue
  private func parseForms(
    _ forms: [String: Any],
    parentTitle: String
  ) -> [(label: String, node: NavigationNode)] {
    var options: [(label: String, node: NavigationNode)] = []

    // Sort keys to maintain consistent order
    let sortedKeys = forms.keys.sorted()

    for key in sortedKeys {
      guard let value = forms[key] else { continue }

      if let stringValue = value as? String {
        // Final value
        options.append((label: key, node: .finalValue(stringValue)))

      } else if let nestedDict = value as? [String: Any],
                let title = nestedDict["title"] as? String,
                let nestedForms = nestedDict["forms"] as? [String: Any] {
        // Has nested forms - need to navigate deeper

        // Check for explicit displayValue, otherwise auto-generate
        let displayValue: String
        if let explicit = nestedDict["displayValue"] as? String {
          displayValue = explicit
        } else {
          displayValue = autoGenerateDisplayValue(from: nestedForms)
        }

        let suboptions = parseForms(nestedForms, parentTitle: title)
        let nextLevel = NavigationLevel(title: title, options: suboptions)

        options.append((label: key, node: .nextLevel(nextLevel, displayValue: displayValue)))
      }
    }

    return options
  }

  /// Auto-generates display value by joining direct child values
  private func autoGenerateDisplayValue(from forms: [String: Any]) -> String {
    var values: [String] = []

    // Sort keys to maintain consistent order
    let sortedKeys = forms.keys.sorted()

    for key in sortedKeys {
      guard let value = forms[key] else { continue }

      if let stringValue = value as? String {
        // Direct string value - use it
        values.append(stringValue)
      }
    }

    return values.joined(separator: "/")
  }
}
