// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

/// Manages loading and parsing of declension contracts.
class DeclensionManager {
  static let shared = DeclensionManager()

  private init() {}

  /// Loads declension cases for a language.
  /// - Parameters:
  ///   - language: The language code (e.g., "de", "en").
  /// - Returns: Array of navigation levels representing declension cases.
  func loadDeclensions(language: String) -> [NavigationLevel]? {
    let languageCode = language.lowercased()
    let contract = ContractManager.shared.loadContract(language: languageCode)

    guard let declensionsDict = contract.declensions else {
      return nil
    }

    // Sort by numeric keys.
    let sortedKeys = declensionsDict.keys.sorted { Int($0) ?? 0 < Int($1) ?? 0 }

    var cases: [NavigationLevel] = []

    for key in sortedKeys {
      guard let declension = declensionsDict[key],
            let title = declension.title ?? declension.sectionTitle,
            let forms = declension.declensionForms else {
        continue
      }

      let options = parseForms(forms, parentTitle: title)
      cases.append(NavigationLevel(title: title, options: options))
    }

    return cases
  }

  /// Recursively parses forms with optional displayValue.
  /// - Parameters:
  ///   - forms: The forms dictionary to parse.
  ///   - parentTitle: The title of the parent level.
  /// - Returns: Array of label-node pairs for navigation.
  private func parseForms(
    _ forms: [String: DeclensionForm],
    parentTitle: String
  ) -> [(label: String, node: NavigationNode)] {
    var options: [(label: String, node: NavigationNode)] = []

    for key in forms.keys.sorted() {
      guard let form = forms[key] else { continue }

      switch form {
      case .value(let stringValue):
        options.append((label: key, node: .finalValue(stringValue)))

      case .nested(let nestedDict):
        // Pull title, declensionForms, displayValue out of the nested dict.
        guard case .value(let title) = nestedDict["title"] ?? nestedDict["sectionTitle"] else { continue }
        guard let nestedForms = nestedDict["declensionForms"],
              case .nested(let nestedFormsDict) = nestedForms else { continue }

        let displayValue: String
        if let explicit = nestedDict["displayValue"], case .value(let dv) = explicit {
          displayValue = dv
        } else {
          displayValue = autoGenerateDisplayValue(from: nestedFormsDict)
        }

        let suboptions = parseForms(nestedFormsDict, parentTitle: title)
        let nextLevel = NavigationLevel(title: title, options: suboptions)
        options.append((label: key, node: .nextLevel(nextLevel, displayValue: displayValue)))
      }
    }

    return options
  }

  /// Auto-generates display value by joining direct child values.
  /// - Parameter forms: The forms dictionary.
  /// - Returns: Generated display value string.
  private func autoGenerateDisplayValue(from forms: [String: Any]) -> String {
    var values: [String] = []

    // Sort keys to maintain consistent order.
    let sortedKeys = forms.keys.sorted()

    for key in sortedKeys {
      guard let value = forms[key] else { continue }

      if let stringValue = value as? String {
        values.append(stringValue)
      }
    }

    return values.joined(separator: "/")
  }
}
