// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

/// Manages loading and parsing of declension contracts.
class DeclensionManager {
  static let shared = DeclensionManager()

  private init() {}

  /// Loads declension cases for a language.
  /// - Parameters:
  ///   - language: The language code (e.g., "de", "en").
  /// - Returns: Array of navigation levels representing declension cases.
  func loadDeclensions(language: String) -> [NavigationLevel]? {
    let languageCode = language.lowercased()
    let contract = ContractManager.shared.loadContract(language: languageCode)

    guard let declensionsDict = contract.declensions else {
      return nil
    }

    let sortedKeys = declensionsDict.keys.sorted()

    var cases: [NavigationLevel] = []

    for key in sortedKeys {
      guard let declension = declensionsDict[key],
            let title = declension.title ?? declension.sectionTitle,
            let forms = declension.declensionForms else {
        continue
      }

      let options = parseForms(forms, parentTitle: title)
      cases.append(NavigationLevel(title: title, options: options))
    }

    return cases
  }

  /// Recursively parses forms with optional displayValue.
  /// - Parameters:
  ///   - forms: The forms dictionary to parse.
  ///   - parentTitle: The title of the parent level.
  /// - Returns: Array of label-node pairs for navigation.
  private func parseForms(
    _ forms: [Int: DeclensionNode],
    parentTitle: String
  ) -> [(label: String, node: NavigationNode)] {
    var options: [(label: String, node: NavigationNode)] = []

    for key in forms.keys.sorted() {
      guard let form = forms[key] else { continue }

      if let value = form.value, let label = form.label {
        options.append((label: label, node: .finalValue(value)))
      } else if let nestedForms = form.declensionForms, let title = form.title {
        let displayValue = form.displayValue ?? autoGenerateDisplayValue(from: nestedForms)
        let suboptions = parseForms(nestedForms, parentTitle: title)
        let nextLevel = NavigationLevel(title: title, options: suboptions)
        options.append((label: form.label ?? title, node: .nextLevel(nextLevel, displayValue: displayValue)))
      }
    }

    return options
  }

  /// Auto-generates display value by joining direct child values.
  /// - Parameter forms: The forms dictionary.
  /// - Returns: Generated display value string.
  private func autoGenerateDisplayValue(from forms: [Int: DeclensionNode]) -> String {
    forms.keys.sorted()
      .compactMap { forms[$0]?.value }
      .joined(separator: "/")
  }
}
